language: node_js
node_js:
    - "10.15.3"

dist: trusty
services:
    - mongodb
    - redis-server

env:
    - NODE_ENV=ci PORT=3000
cache:
    directories:
        - node_modules
        - client/node_modules
install:
    - yarn
    - yarn run build

script:
    - nohup yarn run start &
    - sleep 5
    - yarn test -- --watchAll=false
